services:
  DomingoLlanes\StrongParametersBundle\Service\ParametersService:
    #alias: "strong_parameters.parameters"
    arguments:
      - "%strong_parameters.resource%"
      - "%strong_parameters.exception%"